// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FindGames.proto

package org.bitcoma.hearts.model.transfered;

public final class FindGamesProtos {
  private FindGamesProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FindGamesRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 game_room_id = 1;
    boolean hasGameRoomId();
    long getGameRoomId();
  }
  public static final class FindGamesRequest extends
      com.google.protobuf.GeneratedMessage
      implements FindGamesRequestOrBuilder {
    // Use FindGamesRequest.newBuilder() to construct.
    private FindGamesRequest(Builder builder) {
      super(builder);
    }
    private FindGamesRequest(boolean noInit) {}
    
    private static final FindGamesRequest defaultInstance;
    public static FindGamesRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public FindGamesRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoma.hearts.model.transfered.FindGamesProtos.internal_static_hearts_FindGamesRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoma.hearts.model.transfered.FindGamesProtos.internal_static_hearts_FindGamesRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 game_room_id = 1;
    public static final int GAME_ROOM_ID_FIELD_NUMBER = 1;
    private long gameRoomId_;
    public boolean hasGameRoomId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getGameRoomId() {
      return gameRoomId_;
    }
    
    private void initFields() {
      gameRoomId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, gameRoomId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, gameRoomId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoma.hearts.model.transfered.FindGamesProtos.internal_static_hearts_FindGamesRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoma.hearts.model.transfered.FindGamesProtos.internal_static_hearts_FindGamesRequest_fieldAccessorTable;
      }
      
      // Construct using org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        gameRoomId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest.getDescriptor();
      }
      
      public org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest getDefaultInstanceForType() {
        return org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest.getDefaultInstance();
      }
      
      public org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest build() {
        org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest buildPartial() {
        org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest result = new org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gameRoomId_ = gameRoomId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest) {
          return mergeFrom((org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest other) {
        if (other == org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest.getDefaultInstance()) return this;
        if (other.hasGameRoomId()) {
          setGameRoomId(other.getGameRoomId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gameRoomId_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 game_room_id = 1;
      private long gameRoomId_ ;
      public boolean hasGameRoomId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getGameRoomId() {
        return gameRoomId_;
      }
      public Builder setGameRoomId(long value) {
        bitField0_ |= 0x00000001;
        gameRoomId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameRoomId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gameRoomId_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:hearts.FindGamesRequest)
    }
    
    static {
      defaultInstance = new FindGamesRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hearts.FindGamesRequest)
  }
  
  public interface FindGamesResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .hearts.GameInfo game_room_infos = 1;
    java.util.List<org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo> 
        getGameRoomInfosList();
    org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo getGameRoomInfos(int index);
    int getGameRoomInfosCount();
    java.util.List<? extends org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder> 
        getGameRoomInfosOrBuilderList();
    org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder getGameRoomInfosOrBuilder(
        int index);
  }
  public static final class FindGamesResponse extends
      com.google.protobuf.GeneratedMessage
      implements FindGamesResponseOrBuilder {
    // Use FindGamesResponse.newBuilder() to construct.
    private FindGamesResponse(Builder builder) {
      super(builder);
    }
    private FindGamesResponse(boolean noInit) {}
    
    private static final FindGamesResponse defaultInstance;
    public static FindGamesResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public FindGamesResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoma.hearts.model.transfered.FindGamesProtos.internal_static_hearts_FindGamesResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoma.hearts.model.transfered.FindGamesProtos.internal_static_hearts_FindGamesResponse_fieldAccessorTable;
    }
    
    // repeated .hearts.GameInfo game_room_infos = 1;
    public static final int GAME_ROOM_INFOS_FIELD_NUMBER = 1;
    private java.util.List<org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo> gameRoomInfos_;
    public java.util.List<org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo> getGameRoomInfosList() {
      return gameRoomInfos_;
    }
    public java.util.List<? extends org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder> 
        getGameRoomInfosOrBuilderList() {
      return gameRoomInfos_;
    }
    public int getGameRoomInfosCount() {
      return gameRoomInfos_.size();
    }
    public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo getGameRoomInfos(int index) {
      return gameRoomInfos_.get(index);
    }
    public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder getGameRoomInfosOrBuilder(
        int index) {
      return gameRoomInfos_.get(index);
    }
    
    private void initFields() {
      gameRoomInfos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < gameRoomInfos_.size(); i++) {
        output.writeMessage(1, gameRoomInfos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < gameRoomInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gameRoomInfos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoma.hearts.model.transfered.FindGamesProtos.internal_static_hearts_FindGamesResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoma.hearts.model.transfered.FindGamesProtos.internal_static_hearts_FindGamesResponse_fieldAccessorTable;
      }
      
      // Construct using org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGameRoomInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (gameRoomInfosBuilder_ == null) {
          gameRoomInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gameRoomInfosBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse.getDescriptor();
      }
      
      public org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse getDefaultInstanceForType() {
        return org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse.getDefaultInstance();
      }
      
      public org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse build() {
        org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse buildPartial() {
        org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse result = new org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse(this);
        int from_bitField0_ = bitField0_;
        if (gameRoomInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            gameRoomInfos_ = java.util.Collections.unmodifiableList(gameRoomInfos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gameRoomInfos_ = gameRoomInfos_;
        } else {
          result.gameRoomInfos_ = gameRoomInfosBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse) {
          return mergeFrom((org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse other) {
        if (other == org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse.getDefaultInstance()) return this;
        if (gameRoomInfosBuilder_ == null) {
          if (!other.gameRoomInfos_.isEmpty()) {
            if (gameRoomInfos_.isEmpty()) {
              gameRoomInfos_ = other.gameRoomInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGameRoomInfosIsMutable();
              gameRoomInfos_.addAll(other.gameRoomInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.gameRoomInfos_.isEmpty()) {
            if (gameRoomInfosBuilder_.isEmpty()) {
              gameRoomInfosBuilder_.dispose();
              gameRoomInfosBuilder_ = null;
              gameRoomInfos_ = other.gameRoomInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gameRoomInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGameRoomInfosFieldBuilder() : null;
            } else {
              gameRoomInfosBuilder_.addAllMessages(other.gameRoomInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder subBuilder = org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGameRoomInfos(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .hearts.GameInfo game_room_infos = 1;
      private java.util.List<org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo> gameRoomInfos_ =
        java.util.Collections.emptyList();
      private void ensureGameRoomInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          gameRoomInfos_ = new java.util.ArrayList<org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo>(gameRoomInfos_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder> gameRoomInfosBuilder_;
      
      public java.util.List<org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo> getGameRoomInfosList() {
        if (gameRoomInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gameRoomInfos_);
        } else {
          return gameRoomInfosBuilder_.getMessageList();
        }
      }
      public int getGameRoomInfosCount() {
        if (gameRoomInfosBuilder_ == null) {
          return gameRoomInfos_.size();
        } else {
          return gameRoomInfosBuilder_.getCount();
        }
      }
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo getGameRoomInfos(int index) {
        if (gameRoomInfosBuilder_ == null) {
          return gameRoomInfos_.get(index);
        } else {
          return gameRoomInfosBuilder_.getMessage(index);
        }
      }
      public Builder setGameRoomInfos(
          int index, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo value) {
        if (gameRoomInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameRoomInfosIsMutable();
          gameRoomInfos_.set(index, value);
          onChanged();
        } else {
          gameRoomInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGameRoomInfos(
          int index, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder builderForValue) {
        if (gameRoomInfosBuilder_ == null) {
          ensureGameRoomInfosIsMutable();
          gameRoomInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          gameRoomInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGameRoomInfos(org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo value) {
        if (gameRoomInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameRoomInfosIsMutable();
          gameRoomInfos_.add(value);
          onChanged();
        } else {
          gameRoomInfosBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGameRoomInfos(
          int index, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo value) {
        if (gameRoomInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameRoomInfosIsMutable();
          gameRoomInfos_.add(index, value);
          onChanged();
        } else {
          gameRoomInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGameRoomInfos(
          org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder builderForValue) {
        if (gameRoomInfosBuilder_ == null) {
          ensureGameRoomInfosIsMutable();
          gameRoomInfos_.add(builderForValue.build());
          onChanged();
        } else {
          gameRoomInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGameRoomInfos(
          int index, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder builderForValue) {
        if (gameRoomInfosBuilder_ == null) {
          ensureGameRoomInfosIsMutable();
          gameRoomInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          gameRoomInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGameRoomInfos(
          java.lang.Iterable<? extends org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo> values) {
        if (gameRoomInfosBuilder_ == null) {
          ensureGameRoomInfosIsMutable();
          super.addAll(values, gameRoomInfos_);
          onChanged();
        } else {
          gameRoomInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGameRoomInfos() {
        if (gameRoomInfosBuilder_ == null) {
          gameRoomInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gameRoomInfosBuilder_.clear();
        }
        return this;
      }
      public Builder removeGameRoomInfos(int index) {
        if (gameRoomInfosBuilder_ == null) {
          ensureGameRoomInfosIsMutable();
          gameRoomInfos_.remove(index);
          onChanged();
        } else {
          gameRoomInfosBuilder_.remove(index);
        }
        return this;
      }
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder getGameRoomInfosBuilder(
          int index) {
        return getGameRoomInfosFieldBuilder().getBuilder(index);
      }
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder getGameRoomInfosOrBuilder(
          int index) {
        if (gameRoomInfosBuilder_ == null) {
          return gameRoomInfos_.get(index);  } else {
          return gameRoomInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder> 
           getGameRoomInfosOrBuilderList() {
        if (gameRoomInfosBuilder_ != null) {
          return gameRoomInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gameRoomInfos_);
        }
      }
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder addGameRoomInfosBuilder() {
        return getGameRoomInfosFieldBuilder().addBuilder(
            org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.getDefaultInstance());
      }
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder addGameRoomInfosBuilder(
          int index) {
        return getGameRoomInfosFieldBuilder().addBuilder(
            index, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.getDefaultInstance());
      }
      public java.util.List<org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder> 
           getGameRoomInfosBuilderList() {
        return getGameRoomInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder> 
          getGameRoomInfosFieldBuilder() {
        if (gameRoomInfosBuilder_ == null) {
          gameRoomInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder, org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder>(
                  gameRoomInfos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          gameRoomInfos_ = null;
        }
        return gameRoomInfosBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:hearts.FindGamesResponse)
    }
    
    static {
      defaultInstance = new FindGamesResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hearts.FindGamesResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearts_FindGamesRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearts_FindGamesRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearts_FindGamesResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearts_FindGamesResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017FindGames.proto\022\006hearts\032\020GameStruct.pr" +
      "oto\"(\n\020FindGamesRequest\022\024\n\014game_room_id\030" +
      "\001 \001(\004\">\n\021FindGamesResponse\022)\n\017game_room_" +
      "infos\030\001 \003(\0132\020.hearts.GameInfoB8\n#org.bit" +
      "coma.hearts.model.transferedB\017FindGamesP" +
      "rotosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hearts_FindGamesRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hearts_FindGamesRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearts_FindGamesRequest_descriptor,
              new java.lang.String[] { "GameRoomId", },
              org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest.class,
              org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesRequest.Builder.class);
          internal_static_hearts_FindGamesResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_hearts_FindGamesResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearts_FindGamesResponse_descriptor,
              new java.lang.String[] { "GameRoomInfos", },
              org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse.class,
              org.bitcoma.hearts.model.transfered.FindGamesProtos.FindGamesResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.bitcoma.hearts.model.transfered.GameStructProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
