// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameStruct.proto

package org.bitcoma.hearts.model.transfered;

public final class GameStructProtos {
  private GameStructProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 game_id = 1;
    boolean hasGameId();
    long getGameId();
    
    // optional string game_name = 2;
    boolean hasGameName();
    String getGameName();
    
    // repeated .hearts.PlayerInfo players = 3;
    java.util.List<org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo> 
        getPlayersList();
    org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getPlayers(int index);
    int getPlayersCount();
    java.util.List<? extends org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> 
        getPlayersOrBuilderList();
    org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getPlayersOrBuilder(
        int index);
    
    // optional uint32 max_number_of_players = 4;
    boolean hasMaxNumberOfPlayers();
    int getMaxNumberOfPlayers();
  }
  public static final class GameInfo extends
      com.google.protobuf.GeneratedMessage
      implements GameInfoOrBuilder {
    // Use GameInfo.newBuilder() to construct.
    private GameInfo(Builder builder) {
      super(builder);
    }
    private GameInfo(boolean noInit) {}
    
    private static final GameInfo defaultInstance;
    public static GameInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoma.hearts.model.transfered.GameStructProtos.internal_static_hearts_GameInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoma.hearts.model.transfered.GameStructProtos.internal_static_hearts_GameInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 game_id = 1;
    public static final int GAME_ID_FIELD_NUMBER = 1;
    private long gameId_;
    public boolean hasGameId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getGameId() {
      return gameId_;
    }
    
    // optional string game_name = 2;
    public static final int GAME_NAME_FIELD_NUMBER = 2;
    private Object gameName_;
    public boolean hasGameName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getGameName() {
      Object ref = gameName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gameName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGameNameBytes() {
      Object ref = gameName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gameName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .hearts.PlayerInfo players = 3;
    public static final int PLAYERS_FIELD_NUMBER = 3;
    private java.util.List<org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo> players_;
    public java.util.List<org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo> getPlayersList() {
      return players_;
    }
    public java.util.List<? extends org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> 
        getPlayersOrBuilderList() {
      return players_;
    }
    public int getPlayersCount() {
      return players_.size();
    }
    public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getPlayers(int index) {
      return players_.get(index);
    }
    public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getPlayersOrBuilder(
        int index) {
      return players_.get(index);
    }
    
    // optional uint32 max_number_of_players = 4;
    public static final int MAX_NUMBER_OF_PLAYERS_FIELD_NUMBER = 4;
    private int maxNumberOfPlayers_;
    public boolean hasMaxNumberOfPlayers() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getMaxNumberOfPlayers() {
      return maxNumberOfPlayers_;
    }
    
    private void initFields() {
      gameId_ = 0L;
      gameName_ = "";
      players_ = java.util.Collections.emptyList();
      maxNumberOfPlayers_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, gameId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getGameNameBytes());
      }
      for (int i = 0; i < players_.size(); i++) {
        output.writeMessage(3, players_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, maxNumberOfPlayers_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, gameId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getGameNameBytes());
      }
      for (int i = 0; i < players_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, players_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, maxNumberOfPlayers_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoma.hearts.model.transfered.GameStructProtos.internal_static_hearts_GameInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoma.hearts.model.transfered.GameStructProtos.internal_static_hearts_GameInfo_fieldAccessorTable;
      }
      
      // Construct using org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        gameId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        gameName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          playersBuilder_.clear();
        }
        maxNumberOfPlayers_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.getDescriptor();
      }
      
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo getDefaultInstanceForType() {
        return org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.getDefaultInstance();
      }
      
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo build() {
        org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo buildPartial() {
        org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo result = new org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gameId_ = gameId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gameName_ = gameName_;
        if (playersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            players_ = java.util.Collections.unmodifiableList(players_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.players_ = players_;
        } else {
          result.players_ = playersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxNumberOfPlayers_ = maxNumberOfPlayers_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo) {
          return mergeFrom((org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo other) {
        if (other == org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.getDefaultInstance()) return this;
        if (other.hasGameId()) {
          setGameId(other.getGameId());
        }
        if (other.hasGameName()) {
          setGameName(other.getGameName());
        }
        if (playersBuilder_ == null) {
          if (!other.players_.isEmpty()) {
            if (players_.isEmpty()) {
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePlayersIsMutable();
              players_.addAll(other.players_);
            }
            onChanged();
          }
        } else {
          if (!other.players_.isEmpty()) {
            if (playersBuilder_.isEmpty()) {
              playersBuilder_.dispose();
              playersBuilder_ = null;
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000004);
              playersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayersFieldBuilder() : null;
            } else {
              playersBuilder_.addAllMessages(other.players_);
            }
          }
        }
        if (other.hasMaxNumberOfPlayers()) {
          setMaxNumberOfPlayers(other.getMaxNumberOfPlayers());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gameId_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              gameName_ = input.readBytes();
              break;
            }
            case 26: {
              org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder subBuilder = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPlayers(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              maxNumberOfPlayers_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 game_id = 1;
      private long gameId_ ;
      public boolean hasGameId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getGameId() {
        return gameId_;
      }
      public Builder setGameId(long value) {
        bitField0_ |= 0x00000001;
        gameId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gameId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string game_name = 2;
      private Object gameName_ = "";
      public boolean hasGameName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getGameName() {
        Object ref = gameName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gameName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGameName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        gameName_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gameName_ = getDefaultInstance().getGameName();
        onChanged();
        return this;
      }
      void setGameName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        gameName_ = value;
        onChanged();
      }
      
      // repeated .hearts.PlayerInfo players = 3;
      private java.util.List<org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo> players_ =
        java.util.Collections.emptyList();
      private void ensurePlayersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          players_ = new java.util.ArrayList<org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo>(players_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> playersBuilder_;
      
      public java.util.List<org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo> getPlayersList() {
        if (playersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(players_);
        } else {
          return playersBuilder_.getMessageList();
        }
      }
      public int getPlayersCount() {
        if (playersBuilder_ == null) {
          return players_.size();
        } else {
          return playersBuilder_.getCount();
        }
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getPlayers(int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);
        } else {
          return playersBuilder_.getMessage(index);
        }
      }
      public Builder setPlayers(
          int index, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.set(index, value);
          onChanged();
        } else {
          playersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPlayers(
          int index, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.set(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPlayers(org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(value);
          onChanged();
        } else {
          playersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPlayers(
          int index, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(index, value);
          onChanged();
        } else {
          playersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPlayers(
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPlayers(
          int index, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPlayers(
          java.lang.Iterable<? extends org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo> values) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          super.addAll(values, players_);
          onChanged();
        } else {
          playersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPlayers() {
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          playersBuilder_.clear();
        }
        return this;
      }
      public Builder removePlayers(int index) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.remove(index);
          onChanged();
        } else {
          playersBuilder_.remove(index);
        }
        return this;
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder getPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().getBuilder(index);
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getPlayersOrBuilder(
          int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);  } else {
          return playersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> 
           getPlayersOrBuilderList() {
        if (playersBuilder_ != null) {
          return playersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(players_);
        }
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder addPlayersBuilder() {
        return getPlayersFieldBuilder().addBuilder(
            org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance());
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder addPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().addBuilder(
            index, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance());
      }
      public java.util.List<org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder> 
           getPlayersBuilderList() {
        return getPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> 
          getPlayersFieldBuilder() {
        if (playersBuilder_ == null) {
          playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder>(
                  players_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          players_ = null;
        }
        return playersBuilder_;
      }
      
      // optional uint32 max_number_of_players = 4;
      private int maxNumberOfPlayers_ ;
      public boolean hasMaxNumberOfPlayers() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getMaxNumberOfPlayers() {
        return maxNumberOfPlayers_;
      }
      public Builder setMaxNumberOfPlayers(int value) {
        bitField0_ |= 0x00000008;
        maxNumberOfPlayers_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxNumberOfPlayers() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxNumberOfPlayers_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:hearts.GameInfo)
    }
    
    static {
      defaultInstance = new GameInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hearts.GameInfo)
  }
  
  public interface GameRoomInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 game_room_id = 1;
    boolean hasGameRoomId();
    long getGameRoomId();
    
    // optional string game_room_name = 2;
    boolean hasGameRoomName();
    String getGameRoomName();
  }
  public static final class GameRoomInfo extends
      com.google.protobuf.GeneratedMessage
      implements GameRoomInfoOrBuilder {
    // Use GameRoomInfo.newBuilder() to construct.
    private GameRoomInfo(Builder builder) {
      super(builder);
    }
    private GameRoomInfo(boolean noInit) {}
    
    private static final GameRoomInfo defaultInstance;
    public static GameRoomInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameRoomInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoma.hearts.model.transfered.GameStructProtos.internal_static_hearts_GameRoomInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoma.hearts.model.transfered.GameStructProtos.internal_static_hearts_GameRoomInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 game_room_id = 1;
    public static final int GAME_ROOM_ID_FIELD_NUMBER = 1;
    private long gameRoomId_;
    public boolean hasGameRoomId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getGameRoomId() {
      return gameRoomId_;
    }
    
    // optional string game_room_name = 2;
    public static final int GAME_ROOM_NAME_FIELD_NUMBER = 2;
    private Object gameRoomName_;
    public boolean hasGameRoomName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getGameRoomName() {
      Object ref = gameRoomName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gameRoomName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGameRoomNameBytes() {
      Object ref = gameRoomName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gameRoomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      gameRoomId_ = 0L;
      gameRoomName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, gameRoomId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getGameRoomNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, gameRoomId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getGameRoomNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoma.hearts.model.transfered.GameStructProtos.internal_static_hearts_GameRoomInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoma.hearts.model.transfered.GameStructProtos.internal_static_hearts_GameRoomInfo_fieldAccessorTable;
      }
      
      // Construct using org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        gameRoomId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        gameRoomName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo.getDescriptor();
      }
      
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo getDefaultInstanceForType() {
        return org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo.getDefaultInstance();
      }
      
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo build() {
        org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo buildPartial() {
        org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo result = new org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gameRoomId_ = gameRoomId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gameRoomName_ = gameRoomName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo) {
          return mergeFrom((org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo other) {
        if (other == org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo.getDefaultInstance()) return this;
        if (other.hasGameRoomId()) {
          setGameRoomId(other.getGameRoomId());
        }
        if (other.hasGameRoomName()) {
          setGameRoomName(other.getGameRoomName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gameRoomId_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              gameRoomName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 game_room_id = 1;
      private long gameRoomId_ ;
      public boolean hasGameRoomId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getGameRoomId() {
        return gameRoomId_;
      }
      public Builder setGameRoomId(long value) {
        bitField0_ |= 0x00000001;
        gameRoomId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameRoomId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gameRoomId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string game_room_name = 2;
      private Object gameRoomName_ = "";
      public boolean hasGameRoomName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getGameRoomName() {
        Object ref = gameRoomName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gameRoomName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGameRoomName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        gameRoomName_ = value;
        onChanged();
        return this;
      }
      public Builder clearGameRoomName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gameRoomName_ = getDefaultInstance().getGameRoomName();
        onChanged();
        return this;
      }
      void setGameRoomName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        gameRoomName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:hearts.GameRoomInfo)
    }
    
    static {
      defaultInstance = new GameRoomInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hearts.GameRoomInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearts_GameInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearts_GameInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearts_GameRoomInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearts_GameRoomInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020GameStruct.proto\022\006hearts\032\022PlayerStruct" +
      ".proto\"r\n\010GameInfo\022\017\n\007game_id\030\001 \001(\004\022\021\n\tg" +
      "ame_name\030\002 \001(\t\022#\n\007players\030\003 \003(\0132\022.hearts" +
      ".PlayerInfo\022\035\n\025max_number_of_players\030\004 \001" +
      "(\r\"<\n\014GameRoomInfo\022\024\n\014game_room_id\030\001 \001(\004" +
      "\022\026\n\016game_room_name\030\002 \001(\tB9\n#org.bitcoma." +
      "hearts.model.transferedB\020GameStructProto" +
      "sH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hearts_GameInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hearts_GameInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearts_GameInfo_descriptor,
              new java.lang.String[] { "GameId", "GameName", "Players", "MaxNumberOfPlayers", },
              org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.class,
              org.bitcoma.hearts.model.transfered.GameStructProtos.GameInfo.Builder.class);
          internal_static_hearts_GameRoomInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_hearts_GameRoomInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearts_GameRoomInfo_descriptor,
              new java.lang.String[] { "GameRoomId", "GameRoomName", },
              org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo.class,
              org.bitcoma.hearts.model.transfered.GameStructProtos.GameRoomInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
