// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplacePlayer.proto

package org.bitcoma.hearts.model.transfered;

public final class ReplacePlayerProtos {
  private ReplacePlayerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReplacePlayerResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .hearts.PlayerInfo removed_player = 1;
    boolean hasRemovedPlayer();
    org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getRemovedPlayer();
    org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getRemovedPlayerOrBuilder();
    
    // optional .hearts.PlayerInfo added_player = 2;
    boolean hasAddedPlayer();
    org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getAddedPlayer();
    org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getAddedPlayerOrBuilder();
  }
  public static final class ReplacePlayerResponse extends
      com.google.protobuf.GeneratedMessage
      implements ReplacePlayerResponseOrBuilder {
    // Use ReplacePlayerResponse.newBuilder() to construct.
    private ReplacePlayerResponse(Builder builder) {
      super(builder);
    }
    private ReplacePlayerResponse(boolean noInit) {}
    
    private static final ReplacePlayerResponse defaultInstance;
    public static ReplacePlayerResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReplacePlayerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.internal_static_hearts_ReplacePlayerResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.internal_static_hearts_ReplacePlayerResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .hearts.PlayerInfo removed_player = 1;
    public static final int REMOVED_PLAYER_FIELD_NUMBER = 1;
    private org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo removedPlayer_;
    public boolean hasRemovedPlayer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getRemovedPlayer() {
      return removedPlayer_;
    }
    public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getRemovedPlayerOrBuilder() {
      return removedPlayer_;
    }
    
    // optional .hearts.PlayerInfo added_player = 2;
    public static final int ADDED_PLAYER_FIELD_NUMBER = 2;
    private org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo addedPlayer_;
    public boolean hasAddedPlayer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getAddedPlayer() {
      return addedPlayer_;
    }
    public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getAddedPlayerOrBuilder() {
      return addedPlayer_;
    }
    
    private void initFields() {
      removedPlayer_ = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance();
      addedPlayer_ = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, removedPlayer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, addedPlayer_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, removedPlayer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, addedPlayer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.internal_static_hearts_ReplacePlayerResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.internal_static_hearts_ReplacePlayerResponse_fieldAccessorTable;
      }
      
      // Construct using org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRemovedPlayerFieldBuilder();
          getAddedPlayerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (removedPlayerBuilder_ == null) {
          removedPlayer_ = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance();
        } else {
          removedPlayerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (addedPlayerBuilder_ == null) {
          addedPlayer_ = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance();
        } else {
          addedPlayerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse.getDescriptor();
      }
      
      public org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse getDefaultInstanceForType() {
        return org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse.getDefaultInstance();
      }
      
      public org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse build() {
        org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse buildPartial() {
        org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse result = new org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (removedPlayerBuilder_ == null) {
          result.removedPlayer_ = removedPlayer_;
        } else {
          result.removedPlayer_ = removedPlayerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (addedPlayerBuilder_ == null) {
          result.addedPlayer_ = addedPlayer_;
        } else {
          result.addedPlayer_ = addedPlayerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse) {
          return mergeFrom((org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse other) {
        if (other == org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse.getDefaultInstance()) return this;
        if (other.hasRemovedPlayer()) {
          mergeRemovedPlayer(other.getRemovedPlayer());
        }
        if (other.hasAddedPlayer()) {
          mergeAddedPlayer(other.getAddedPlayer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder subBuilder = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.newBuilder();
              if (hasRemovedPlayer()) {
                subBuilder.mergeFrom(getRemovedPlayer());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRemovedPlayer(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder subBuilder = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.newBuilder();
              if (hasAddedPlayer()) {
                subBuilder.mergeFrom(getAddedPlayer());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAddedPlayer(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .hearts.PlayerInfo removed_player = 1;
      private org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo removedPlayer_ = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> removedPlayerBuilder_;
      public boolean hasRemovedPlayer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getRemovedPlayer() {
        if (removedPlayerBuilder_ == null) {
          return removedPlayer_;
        } else {
          return removedPlayerBuilder_.getMessage();
        }
      }
      public Builder setRemovedPlayer(org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo value) {
        if (removedPlayerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          removedPlayer_ = value;
          onChanged();
        } else {
          removedPlayerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setRemovedPlayer(
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder builderForValue) {
        if (removedPlayerBuilder_ == null) {
          removedPlayer_ = builderForValue.build();
          onChanged();
        } else {
          removedPlayerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeRemovedPlayer(org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo value) {
        if (removedPlayerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              removedPlayer_ != org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance()) {
            removedPlayer_ =
              org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.newBuilder(removedPlayer_).mergeFrom(value).buildPartial();
          } else {
            removedPlayer_ = value;
          }
          onChanged();
        } else {
          removedPlayerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearRemovedPlayer() {
        if (removedPlayerBuilder_ == null) {
          removedPlayer_ = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance();
          onChanged();
        } else {
          removedPlayerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder getRemovedPlayerBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRemovedPlayerFieldBuilder().getBuilder();
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getRemovedPlayerOrBuilder() {
        if (removedPlayerBuilder_ != null) {
          return removedPlayerBuilder_.getMessageOrBuilder();
        } else {
          return removedPlayer_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> 
          getRemovedPlayerFieldBuilder() {
        if (removedPlayerBuilder_ == null) {
          removedPlayerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder>(
                  removedPlayer_,
                  getParentForChildren(),
                  isClean());
          removedPlayer_ = null;
        }
        return removedPlayerBuilder_;
      }
      
      // optional .hearts.PlayerInfo added_player = 2;
      private org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo addedPlayer_ = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> addedPlayerBuilder_;
      public boolean hasAddedPlayer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo getAddedPlayer() {
        if (addedPlayerBuilder_ == null) {
          return addedPlayer_;
        } else {
          return addedPlayerBuilder_.getMessage();
        }
      }
      public Builder setAddedPlayer(org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo value) {
        if (addedPlayerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          addedPlayer_ = value;
          onChanged();
        } else {
          addedPlayerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setAddedPlayer(
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder builderForValue) {
        if (addedPlayerBuilder_ == null) {
          addedPlayer_ = builderForValue.build();
          onChanged();
        } else {
          addedPlayerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeAddedPlayer(org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo value) {
        if (addedPlayerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              addedPlayer_ != org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance()) {
            addedPlayer_ =
              org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.newBuilder(addedPlayer_).mergeFrom(value).buildPartial();
          } else {
            addedPlayer_ = value;
          }
          onChanged();
        } else {
          addedPlayerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearAddedPlayer() {
        if (addedPlayerBuilder_ == null) {
          addedPlayer_ = org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.getDefaultInstance();
          onChanged();
        } else {
          addedPlayerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder getAddedPlayerBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getAddedPlayerFieldBuilder().getBuilder();
      }
      public org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder getAddedPlayerOrBuilder() {
        if (addedPlayerBuilder_ != null) {
          return addedPlayerBuilder_.getMessageOrBuilder();
        } else {
          return addedPlayer_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder> 
          getAddedPlayerFieldBuilder() {
        if (addedPlayerBuilder_ == null) {
          addedPlayerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfo.Builder, org.bitcoma.hearts.model.transfered.PlayerStructProtos.PlayerInfoOrBuilder>(
                  addedPlayer_,
                  getParentForChildren(),
                  isClean());
          addedPlayer_ = null;
        }
        return addedPlayerBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:hearts.ReplacePlayerResponse)
    }
    
    static {
      defaultInstance = new ReplacePlayerResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hearts.ReplacePlayerResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearts_ReplacePlayerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearts_ReplacePlayerResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ReplacePlayer.proto\022\006hearts\032\022PlayerStr" +
      "uct.proto\"m\n\025ReplacePlayerResponse\022*\n\016re" +
      "moved_player\030\001 \001(\0132\022.hearts.PlayerInfo\022(" +
      "\n\014added_player\030\002 \001(\0132\022.hearts.PlayerInfo" +
      "B<\n#org.bitcoma.hearts.model.transferedB" +
      "\023ReplacePlayerProtosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hearts_ReplacePlayerResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hearts_ReplacePlayerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearts_ReplacePlayerResponse_descriptor,
              new java.lang.String[] { "RemovedPlayer", "AddedPlayer", },
              org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse.class,
              org.bitcoma.hearts.model.transfered.ReplacePlayerProtos.ReplacePlayerResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.bitcoma.hearts.model.transfered.PlayerStructProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
