// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScoreUpdate.proto

package org.bitcoma.hearts.model.transfered;

public final class ScoreUpdateProtos {
  private ScoreUpdateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ScoreUpdateResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .hearts.ScoreUpdateResponse.ScoreInfo user_scores = 1;
    java.util.List<org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo> 
        getUserScoresList();
    org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo getUserScores(int index);
    int getUserScoresCount();
    java.util.List<? extends org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder> 
        getUserScoresOrBuilderList();
    org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder getUserScoresOrBuilder(
        int index);
  }
  public static final class ScoreUpdateResponse extends
      com.google.protobuf.GeneratedMessage
      implements ScoreUpdateResponseOrBuilder {
    // Use ScoreUpdateResponse.newBuilder() to construct.
    private ScoreUpdateResponse(Builder builder) {
      super(builder);
    }
    private ScoreUpdateResponse(boolean noInit) {}
    
    private static final ScoreUpdateResponse defaultInstance;
    public static ScoreUpdateResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ScoreUpdateResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.internal_static_hearts_ScoreUpdateResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.internal_static_hearts_ScoreUpdateResponse_fieldAccessorTable;
    }
    
    public interface ScoreInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional uint64 user_id = 1;
      boolean hasUserId();
      long getUserId();
      
      // optional uint32 round_score = 2;
      boolean hasRoundScore();
      int getRoundScore();
      
      // optional uint32 game_score = 3;
      boolean hasGameScore();
      int getGameScore();
    }
    public static final class ScoreInfo extends
        com.google.protobuf.GeneratedMessage
        implements ScoreInfoOrBuilder {
      // Use ScoreInfo.newBuilder() to construct.
      private ScoreInfo(Builder builder) {
        super(builder);
      }
      private ScoreInfo(boolean noInit) {}
      
      private static final ScoreInfo defaultInstance;
      public static ScoreInfo getDefaultInstance() {
        return defaultInstance;
      }
      
      public ScoreInfo getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.internal_static_hearts_ScoreUpdateResponse_ScoreInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.internal_static_hearts_ScoreUpdateResponse_ScoreInfo_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional uint64 user_id = 1;
      public static final int USER_ID_FIELD_NUMBER = 1;
      private long userId_;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getUserId() {
        return userId_;
      }
      
      // optional uint32 round_score = 2;
      public static final int ROUND_SCORE_FIELD_NUMBER = 2;
      private int roundScore_;
      public boolean hasRoundScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getRoundScore() {
        return roundScore_;
      }
      
      // optional uint32 game_score = 3;
      public static final int GAME_SCORE_FIELD_NUMBER = 3;
      private int gameScore_;
      public boolean hasGameScore() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getGameScore() {
        return gameScore_;
      }
      
      private void initFields() {
        userId_ = 0L;
        roundScore_ = 0;
        gameScore_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt64(1, userId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, roundScore_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeUInt32(3, gameScore_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(1, userId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, roundScore_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, gameScore_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      @java.lang.Override
      protected Object writeReplace() throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.internal_static_hearts_ScoreUpdateResponse_ScoreInfo_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.internal_static_hearts_ScoreUpdateResponse_ScoreInfo_fieldAccessorTable;
        }
        
        // Construct using org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          userId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          roundScore_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          gameScore_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.getDescriptor();
        }
        
        public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo getDefaultInstanceForType() {
          return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.getDefaultInstance();
        }
        
        public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo build() {
          org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo buildPartial() {
          org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo result = new org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.userId_ = userId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.roundScore_ = roundScore_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.gameScore_ = gameScore_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo) {
            return mergeFrom((org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo other) {
          if (other == org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.getDefaultInstance()) return this;
          if (other.hasUserId()) {
            setUserId(other.getUserId());
          }
          if (other.hasRoundScore()) {
            setRoundScore(other.getRoundScore());
          }
          if (other.hasGameScore()) {
            setGameScore(other.getGameScore());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                userId_ = input.readUInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                roundScore_ = input.readUInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                gameScore_ = input.readUInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional uint64 user_id = 1;
        private long userId_ ;
        public boolean hasUserId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public long getUserId() {
          return userId_;
        }
        public Builder setUserId(long value) {
          bitField0_ |= 0x00000001;
          userId_ = value;
          onChanged();
          return this;
        }
        public Builder clearUserId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          userId_ = 0L;
          onChanged();
          return this;
        }
        
        // optional uint32 round_score = 2;
        private int roundScore_ ;
        public boolean hasRoundScore() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getRoundScore() {
          return roundScore_;
        }
        public Builder setRoundScore(int value) {
          bitField0_ |= 0x00000002;
          roundScore_ = value;
          onChanged();
          return this;
        }
        public Builder clearRoundScore() {
          bitField0_ = (bitField0_ & ~0x00000002);
          roundScore_ = 0;
          onChanged();
          return this;
        }
        
        // optional uint32 game_score = 3;
        private int gameScore_ ;
        public boolean hasGameScore() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getGameScore() {
          return gameScore_;
        }
        public Builder setGameScore(int value) {
          bitField0_ |= 0x00000004;
          gameScore_ = value;
          onChanged();
          return this;
        }
        public Builder clearGameScore() {
          bitField0_ = (bitField0_ & ~0x00000004);
          gameScore_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:hearts.ScoreUpdateResponse.ScoreInfo)
      }
      
      static {
        defaultInstance = new ScoreInfo(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:hearts.ScoreUpdateResponse.ScoreInfo)
    }
    
    // repeated .hearts.ScoreUpdateResponse.ScoreInfo user_scores = 1;
    public static final int USER_SCORES_FIELD_NUMBER = 1;
    private java.util.List<org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo> userScores_;
    public java.util.List<org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo> getUserScoresList() {
      return userScores_;
    }
    public java.util.List<? extends org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder> 
        getUserScoresOrBuilderList() {
      return userScores_;
    }
    public int getUserScoresCount() {
      return userScores_.size();
    }
    public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo getUserScores(int index) {
      return userScores_.get(index);
    }
    public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder getUserScoresOrBuilder(
        int index) {
      return userScores_.get(index);
    }
    
    private void initFields() {
      userScores_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < userScores_.size(); i++) {
        output.writeMessage(1, userScores_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < userScores_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userScores_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.internal_static_hearts_ScoreUpdateResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.internal_static_hearts_ScoreUpdateResponse_fieldAccessorTable;
      }
      
      // Construct using org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserScoresFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (userScoresBuilder_ == null) {
          userScores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userScoresBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.getDescriptor();
      }
      
      public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse getDefaultInstanceForType() {
        return org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.getDefaultInstance();
      }
      
      public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse build() {
        org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse buildPartial() {
        org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse result = new org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse(this);
        int from_bitField0_ = bitField0_;
        if (userScoresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            userScores_ = java.util.Collections.unmodifiableList(userScores_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.userScores_ = userScores_;
        } else {
          result.userScores_ = userScoresBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse) {
          return mergeFrom((org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse other) {
        if (other == org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.getDefaultInstance()) return this;
        if (userScoresBuilder_ == null) {
          if (!other.userScores_.isEmpty()) {
            if (userScores_.isEmpty()) {
              userScores_ = other.userScores_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserScoresIsMutable();
              userScores_.addAll(other.userScores_);
            }
            onChanged();
          }
        } else {
          if (!other.userScores_.isEmpty()) {
            if (userScoresBuilder_.isEmpty()) {
              userScoresBuilder_.dispose();
              userScoresBuilder_ = null;
              userScores_ = other.userScores_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userScoresBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUserScoresFieldBuilder() : null;
            } else {
              userScoresBuilder_.addAllMessages(other.userScores_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder subBuilder = org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUserScores(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .hearts.ScoreUpdateResponse.ScoreInfo user_scores = 1;
      private java.util.List<org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo> userScores_ =
        java.util.Collections.emptyList();
      private void ensureUserScoresIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userScores_ = new java.util.ArrayList<org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo>(userScores_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder> userScoresBuilder_;
      
      public java.util.List<org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo> getUserScoresList() {
        if (userScoresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userScores_);
        } else {
          return userScoresBuilder_.getMessageList();
        }
      }
      public int getUserScoresCount() {
        if (userScoresBuilder_ == null) {
          return userScores_.size();
        } else {
          return userScoresBuilder_.getCount();
        }
      }
      public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo getUserScores(int index) {
        if (userScoresBuilder_ == null) {
          return userScores_.get(index);
        } else {
          return userScoresBuilder_.getMessage(index);
        }
      }
      public Builder setUserScores(
          int index, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo value) {
        if (userScoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserScoresIsMutable();
          userScores_.set(index, value);
          onChanged();
        } else {
          userScoresBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setUserScores(
          int index, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder builderForValue) {
        if (userScoresBuilder_ == null) {
          ensureUserScoresIsMutable();
          userScores_.set(index, builderForValue.build());
          onChanged();
        } else {
          userScoresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addUserScores(org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo value) {
        if (userScoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserScoresIsMutable();
          userScores_.add(value);
          onChanged();
        } else {
          userScoresBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addUserScores(
          int index, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo value) {
        if (userScoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserScoresIsMutable();
          userScores_.add(index, value);
          onChanged();
        } else {
          userScoresBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addUserScores(
          org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder builderForValue) {
        if (userScoresBuilder_ == null) {
          ensureUserScoresIsMutable();
          userScores_.add(builderForValue.build());
          onChanged();
        } else {
          userScoresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addUserScores(
          int index, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder builderForValue) {
        if (userScoresBuilder_ == null) {
          ensureUserScoresIsMutable();
          userScores_.add(index, builderForValue.build());
          onChanged();
        } else {
          userScoresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllUserScores(
          java.lang.Iterable<? extends org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo> values) {
        if (userScoresBuilder_ == null) {
          ensureUserScoresIsMutable();
          super.addAll(values, userScores_);
          onChanged();
        } else {
          userScoresBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearUserScores() {
        if (userScoresBuilder_ == null) {
          userScores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userScoresBuilder_.clear();
        }
        return this;
      }
      public Builder removeUserScores(int index) {
        if (userScoresBuilder_ == null) {
          ensureUserScoresIsMutable();
          userScores_.remove(index);
          onChanged();
        } else {
          userScoresBuilder_.remove(index);
        }
        return this;
      }
      public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder getUserScoresBuilder(
          int index) {
        return getUserScoresFieldBuilder().getBuilder(index);
      }
      public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder getUserScoresOrBuilder(
          int index) {
        if (userScoresBuilder_ == null) {
          return userScores_.get(index);  } else {
          return userScoresBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder> 
           getUserScoresOrBuilderList() {
        if (userScoresBuilder_ != null) {
          return userScoresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userScores_);
        }
      }
      public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder addUserScoresBuilder() {
        return getUserScoresFieldBuilder().addBuilder(
            org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.getDefaultInstance());
      }
      public org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder addUserScoresBuilder(
          int index) {
        return getUserScoresFieldBuilder().addBuilder(
            index, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.getDefaultInstance());
      }
      public java.util.List<org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder> 
           getUserScoresBuilderList() {
        return getUserScoresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder> 
          getUserScoresFieldBuilder() {
        if (userScoresBuilder_ == null) {
          userScoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder, org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfoOrBuilder>(
                  userScores_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          userScores_ = null;
        }
        return userScoresBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:hearts.ScoreUpdateResponse)
    }
    
    static {
      defaultInstance = new ScoreUpdateResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hearts.ScoreUpdateResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearts_ScoreUpdateResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearts_ScoreUpdateResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearts_ScoreUpdateResponse_ScoreInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearts_ScoreUpdateResponse_ScoreInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ScoreUpdate.proto\022\006hearts\"\230\001\n\023ScoreUpd" +
      "ateResponse\022:\n\013user_scores\030\001 \003(\0132%.heart" +
      "s.ScoreUpdateResponse.ScoreInfo\032E\n\tScore" +
      "Info\022\017\n\007user_id\030\001 \001(\004\022\023\n\013round_score\030\002 \001" +
      "(\r\022\022\n\ngame_score\030\003 \001(\rB:\n#org.bitcoma.he" +
      "arts.model.transferedB\021ScoreUpdateProtos" +
      "H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hearts_ScoreUpdateResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hearts_ScoreUpdateResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearts_ScoreUpdateResponse_descriptor,
              new java.lang.String[] { "UserScores", },
              org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.class,
              org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.Builder.class);
          internal_static_hearts_ScoreUpdateResponse_ScoreInfo_descriptor =
            internal_static_hearts_ScoreUpdateResponse_descriptor.getNestedTypes().get(0);
          internal_static_hearts_ScoreUpdateResponse_ScoreInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearts_ScoreUpdateResponse_ScoreInfo_descriptor,
              new java.lang.String[] { "UserId", "RoundScore", "GameScore", },
              org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.class,
              org.bitcoma.hearts.model.transfered.ScoreUpdateProtos.ScoreUpdateResponse.ScoreInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
