// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trick.proto

package org.bitcoma.hearts.model.transfered;

public final class TrickProtos {
  private TrickProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TrickEndedResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 loser_id = 1;
    boolean hasLoserId();
    long getLoserId();
  }
  public static final class TrickEndedResponse extends
      com.google.protobuf.GeneratedMessage
      implements TrickEndedResponseOrBuilder {
    // Use TrickEndedResponse.newBuilder() to construct.
    private TrickEndedResponse(Builder builder) {
      super(builder);
    }
    private TrickEndedResponse(boolean noInit) {}
    
    private static final TrickEndedResponse defaultInstance;
    public static TrickEndedResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public TrickEndedResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoma.hearts.model.transfered.TrickProtos.internal_static_hearts_TrickEndedResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoma.hearts.model.transfered.TrickProtos.internal_static_hearts_TrickEndedResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 loser_id = 1;
    public static final int LOSER_ID_FIELD_NUMBER = 1;
    private long loserId_;
    public boolean hasLoserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLoserId() {
      return loserId_;
    }
    
    private void initFields() {
      loserId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, loserId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, loserId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoma.hearts.model.transfered.TrickProtos.internal_static_hearts_TrickEndedResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoma.hearts.model.transfered.TrickProtos.internal_static_hearts_TrickEndedResponse_fieldAccessorTable;
      }
      
      // Construct using org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        loserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse.getDescriptor();
      }
      
      public org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse getDefaultInstanceForType() {
        return org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse.getDefaultInstance();
      }
      
      public org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse build() {
        org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse buildPartial() {
        org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse result = new org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loserId_ = loserId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse) {
          return mergeFrom((org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse other) {
        if (other == org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse.getDefaultInstance()) return this;
        if (other.hasLoserId()) {
          setLoserId(other.getLoserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              loserId_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 loser_id = 1;
      private long loserId_ ;
      public boolean hasLoserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLoserId() {
        return loserId_;
      }
      public Builder setLoserId(long value) {
        bitField0_ |= 0x00000001;
        loserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loserId_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:hearts.TrickEndedResponse)
    }
    
    static {
      defaultInstance = new TrickEndedResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hearts.TrickEndedResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hearts_TrickEndedResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearts_TrickEndedResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Trick.proto\022\006hearts\"&\n\022TrickEndedRespo" +
      "nse\022\020\n\010loser_id\030\001 \001(\004B4\n#org.bitcoma.hea" +
      "rts.model.transferedB\013TrickProtosH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hearts_TrickEndedResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hearts_TrickEndedResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hearts_TrickEndedResponse_descriptor,
              new java.lang.String[] { "LoserId", },
              org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse.class,
              org.bitcoma.hearts.model.transfered.TrickProtos.TrickEndedResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
